apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: 'node-exporter'
        static_configs:
        - targets: ['k8smaster:9100', 'node1:9100', 'node2:9100']

      - job_name: 'cloudeos-metrics'
        static_configs:
        - targets: ['k8smaster:30988', 'node1:30988', 'node2:30988']